import type { CustomPrice, Order, Product, SizeOption, User } from './types'

const day = 24 * 60 * 60 * 1000
const now = Date.now()

function sz(names: string[], unavailable: string[] = []): SizeOption[] {
  return names.map((name) => ({
    name,
    available: !unavailable.includes(name),
  }))
}

const CLOTHES = ['XS', 'S', 'M', 'L', 'XL', 'XXL']

export const seedUsers: User[] = [
  {
    id: 'u-admin',
    name: 'Shop Admin',
    email: 'admin@resellhub.ph',
    password: 'admin123',
    role: 'admin',
    active: true,
  },
  {
    id: 'u-ana',
    name: 'Ana Cruz',
    email: 'ana@reseller.ph',
    password: 'reseller123',
    role: 'reseller',
    active: true,
  },
  {
    id: 'u-maria',
    name: 'Maria Santos',
    email: 'maria@reseller.ph',
    password: 'reseller123',
    role: 'reseller',
    active: true,
  },
  {
    id: 'u-jane',
    name: 'Jane Dela Rosa',
    email: 'jane@reseller.ph',
    password: 'reseller123',
    role: 'reseller',
    active: true,
  },
  {
    id: 'u-customer',
    name: 'Regular Customer',
    email: 'customer@example.com',
    password: 'customer123',
    role: 'customer',
    active: true,
  },
]

export const seedProducts: Product[] = [
  {
    id: 'p-dress-soraya',
    name: 'SHEIN Casual Dress — Soraya',
    description:
      'Flowy midi dress with a flattering A-line cut. Lightweight fabric, perfect for everyday wear.',
    category: 'Dresses',
    variant: 'Color: Black, Beige',
    sizes: sz(CLOTHES, ['XXL']),
    image: '',
    images: [],
    available: true,
    stockType: 'on_hand',
    regularPrice: 599,
    defaultResellerPrice: 499,
    createdAt: now - 12 * day,
  },
  {
    id: 'p-top-ribbed',
    name: 'SHEIN Basic Ribbed Top',
    description:
      'Stretchy ribbed knit top that hugs well. Great seller, easy to bundle in pairs.',
    category: 'Tops',
    variant: '10 colors',
    sizes: sz(['S', 'M', 'L', 'XL'], ['XL']),
    image: '',
    images: [],
    available: true,
    stockType: 'pre_order',
    regularPrice: 399,
    defaultResellerPrice: 320,
    createdAt: now - 11 * day,
  },
  {
    id: 'p-pants-wide',
    name: 'SHEIN High-Waist Wide-Leg Pants',
    description:
      'Trending wide-leg silhouette with an elastic high waist. Flows nicely and fits most body types.',
    category: 'Bottoms',
    variant: 'Black, Beige, Olive',
    sizes: sz(CLOTHES, ['XS', 'XXL']),
    image: '',
    images: [],
    available: true,
    stockType: 'on_hand',
    regularPrice: 699,
    defaultResellerPrice: 580,
    createdAt: now - 10 * day,
  },
  {
    id: 'p-skirt-satin',
    name: 'SHEIN Satin Maxi Skirt',
    description:
      'Elegant satin maxi skirt with a subtle sheen. Excellent for dressy events.',
    category: 'Bottoms',
    variant: '6 colors',
    sizes: sz(['S', 'M', 'L']),
    image: '',
    images: [],
    available: true,
    stockType: 'pre_order',
    regularPrice: 450,
    defaultResellerPrice: 360,
    createdAt: now - 9 * day,
  },
  {
    id: 'p-blouse-shoulder',
    name: 'SHEIN Off-Shoulder Blouse',
    description:
      'Breezy off-shoulder blouse with ruffled sleeves. Very popular during summer.',
    category: 'Tops',
    variant: 'White, Coral',
    sizes: sz(CLOTHES, ['XXL']),
    image: '',
    images: [],
    available: true,
    stockType: 'on_hand',
    regularPrice: 520,
    defaultResellerPrice: 410,
    createdAt: now - 8 * day,
  },
  {
    id: 'p-playsuit-tie',
    name: 'SHEIN Tie-Front Playsuit',
    description:
      'One-piece playsuit with tie-front detail. Perfect reseller bundle for vacations.',
    category: 'Sets',
    variant: '5 colors',
    sizes: sz(['XS', 'S', 'M', 'L'], ['XS']),
    image: '',
    images: [],
    available: true,
    stockType: 'pre_order',
    regularPrice: 650,
    defaultResellerPrice: 520,
    createdAt: now - 7 * day,
  },
  {
    id: 'p-jumpsuit',
    name: 'SHEIN Sleeveless Jumpsuit',
    description:
      'Tapered jumpsuit with a cinched waist. Office-to-weekend wardrobe staple.',
    category: 'Sets',
    variant: 'Black, Navy',
    sizes: sz(['S', 'M', 'L'], ['L']),
    image: '',
    available: false,
    stockType: 'on_hand',
    regularPrice: 780,
    defaultResellerPrice: 620,
    createdAt: now - 6 * day,
  },
  {
    id: 'p-cardigan',
    name: 'SHEIN Button Knit Cardigan',
    description:
      'Soft knit cardigan, perfect layering piece for cooler evenings.',
    category: 'Outerwear',
    variant: '8 colors',
    sizes: sz(['M', 'L', 'XL']),
    image: '',
    images: [],
    available: true,
    stockType: 'on_hand',
    regularPrice: 480,
    defaultResellerPrice: 380,
    createdAt: now - 5 * day,
  },
  {
    id: 'p-dress-floral',
    name: 'SHEIN Floral Flowy Dress',
    description:
      'Midi dress with an all-over floral print and smocked bodice.',
    category: 'Dresses',
    variant: '4 prints',
    sizes: sz(CLOTHES, []),
    image: '',
    images: [],
    available: true,
    stockType: 'pre_order',
    regularPrice: 720,
    defaultResellerPrice: 570,
    createdAt: now - 4 * day,
  },
  {
    id: 'p-skirt-denim',
    name: 'SHEIN Denim Mini Skirt',
    description: 'Classic denim mini skirt with button front. Easy fast mover.',
    category: 'Bottoms',
    variant: 'Blue, Washed Black',
    sizes: sz(CLOTHES, ['XS', 'XXL']),
    image: '',
    images: [],
    available: true,
    stockType: 'on_hand',
    regularPrice: 380,
    defaultResellerPrice: 300,
    createdAt: now - 3 * day,
  },
]

export const seedCustomPrices: CustomPrice[] = [
  { productId: 'p-dress-soraya', resellerId: 'u-ana', price: 480 },
  { productId: 'p-top-ribbed', resellerId: 'u-ana', price: 300 },
  { productId: 'p-dress-soraya', resellerId: 'u-maria', price: 490 },
  { productId: 'p-dress-soraya', resellerId: 'u-jane', price: 475 },
  { productId: 'p-pants-wide', resellerId: 'u-jane', price: 560 },
]

export const seedOrders: Order[] = [
  {
    id: 'RH-1001',
    resellerId: 'u-ana',
    resellerName: 'Ana Cruz',
    status: 'ordered',
    createdAt: now - 2 * day,
    items: [
      {
        productId: 'p-dress-soraya',
        productName: 'SHEIN Casual Dress — Soraya',
        size: 'M',
        variant: 'Color: Black, Beige',
        image: '',
        quantity: 2,
        unitPrice: 480,
        retailPrice: 599,
      },
      {
        productId: 'p-top-ribbed',
        productName: 'SHEIN Basic Ribbed Top',
        size: 'S',
        variant: '10 colors',
        image: '',
        quantity: 1,
        unitPrice: 300,
        retailPrice: 399,
      },
    ],
  },
  {
    id: 'RH-1002',
    resellerId: 'u-jane',
    resellerName: 'Jane Dela Rosa',
    status: 'completed',
    createdAt: now - 6 * day,
    items: [
      {
        productId: 'p-dress-soraya',
        productName: 'SHEIN Casual Dress — Soraya',
        size: 'S',
        variant: 'Color: Black, Beige',
        image: '',
        quantity: 1,
        unitPrice: 475,
        retailPrice: 599,
      },
      {
        productId: 'p-pants-wide',
        productName: 'SHEIN High-Waist Wide-Leg Pants',
        size: 'M',
        variant: 'Black, Beige, Olive',
        image: '',
        quantity: 1,
        unitPrice: 560,
        retailPrice: 699,
      },
    ],
  },
  {
    id: 'RH-1003',
    resellerId: 'u-maria',
    resellerName: 'Maria Santos',
    status: 'pending',
    createdAt: now - 1 * day,
    notes: 'Please remind me when new pink dresses arrive.',
    items: [
      {
        productId: 'p-dress-soraya',
        productName: 'SHEIN Casual Dress — Soraya',
        size: 'L',
        variant: 'Color: Black, Beige',
        image: '',
        quantity: 2,
        unitPrice: 490,
        retailPrice: 599,
      },
      {
        productId: 'p-skirt-satin',
        productName: 'SHEIN Satin Maxi Skirt',
        size: 'M',
        variant: '6 colors',
        image: '',
        quantity: 1,
        unitPrice: 360,
        retailPrice: 450,
      },
    ],
  },
  {
    id: 'RH-1004',
    resellerId: 'u-ana',
    resellerName: 'Ana Cruz',
    status: 'completed',
    createdAt: now - 9 * day,
    items: [
      {
        productId: 'p-playsuit-tie',
        productName: 'SHEIN Tie-Front Playsuit',
        size: 'S',
        variant: '5 colors',
        image: '',
        quantity: 2,
        unitPrice: 520,
        retailPrice: 650,
      },
      {
        productId: 'p-cardigan',
        productName: 'SHEIN Button Knit Cardigan',
        size: 'L',
        variant: '8 colors',
        image: '',
        quantity: 1,
        unitPrice: 380,
        retailPrice: 480,
      },
    ],
  },
  {
    id: 'RH-1005',
    resellerId: 'u-jane',
    resellerName: 'Jane Dela Rosa',
    status: 'arrived',
    createdAt: now - 0.5 * day,
    items: [
      {
        productId: 'p-jumpsuit',
        productName: 'SHEIN Sleeveless Jumpsuit',
        size: 'M',
        variant: 'Black, Navy',
        image: '',
        quantity: 1,
        unitPrice: 620,
        retailPrice: 780,
      },
      {
        productId: 'p-skirt-denim',
        productName: 'SHEIN Denim Mini Skirt',
        size: 'S',
        variant: 'Blue, Washed Black',
        image: '',
        quantity: 1,
        unitPrice: 300,
        retailPrice: 380,
      },
    ],
  },
  {
    id: 'RH-1006',
    resellerId: 'u-maria',
    resellerName: 'Maria Santos',
    status: 'rejected',
    createdAt: now - 3 * day,
    rejectedReason: 'Item out of stock — reseller requested cancellation.',
    items: [
      {
        productId: 'p-jumpsuit',
        productName: 'SHEIN Sleeveless Jumpsuit',
        size: 'L',
        variant: 'Black, Navy',
        image: '',
        quantity: 1,
        unitPrice: 620,
        retailPrice: 780,
      },
    ],
  },
]